Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead

  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: '*'
          Action: 's3:GetObject'
          Resource: !Join ['', ['arn:aws:s3:::', !Ref MyBucket, '/*']]

  MyObject:
    Type: 'AWS::S3::Bucket'
    Properties:
      Bucket: !Ref MyBucket
      Key: index.html
      Source:
        Url: https://raw.githubusercontent.com/kurch1k/gachiland/master/.github/workflows/index.html

  MyDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt MyBucket.RegionalDomainName
          Id: MyOrigin
          S3OriginConfig:
            OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          CachedMethods:
          - GET
          - HEAD
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: MyOrigin
        ViewerProtocolPolicy: redirect-to-https
