Parameters:
  GitHubUser:
    Type: String
    Default: kurch1k
    Description: kurch1k
  GitHubRepo:
    Type: String
    Default: gachiland
    Description: gachiland
  GitHubBranch:
    Type: String
    Default: master
    Description: master
  GitHubDirectory:
    Type: String
    Default: /.github/workflows/
    Description: gachiland

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: kurchucket
      AccessControl: PublicRead

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]

  S3BucketIndexObject:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3Bucket
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Name
          Value: S3BucketIndexObject
      DeletionPolicy: Retain

  S3BucketIndexObjectDeployment:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import os
          import shutil
          import tempfile
          
          s3 = boto3.resource('s3')
          github_user = os.environ['GitHubUser']
          github_repo = os.environ['GitHubRepo']
          github_branch = os.environ['GitHubBranch']
          key = 'index.html'
          
          with tempfile.TemporaryDirectory() as tmp_dir:
              path = os.path.join(tmp_dir, key)
              url = f'https://raw.githubusercontent.com/{github_user}/{github_repo}/{github_branch}/{key}'
              s3.Bucket(os.environ['S3Bucket']).download_file(key, path)
              shutil.copy(path, '/var/task/index.html')
          
      Handler: index.lambda_handler
      Role: !GetAtt [S3BucketIndexObjectDeploymentRole, Arn]
      Runtime: python3.8

  S3BucketIndexObjectDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReadWrite
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:GetBucketWebsite
                Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]          

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: my-bucket
            DomainName: !GetAtt S3Bucket.WebsiteURL
            S3OriginConfig:
              OriginAccessIdentity: ""
        Enabled: true
