Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: "kurchucket"
      AccessControl: PublicRead

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Join ['', ["arn:aws:s3:::", !Ref S3Bucket, "/*"]]

  S3IndexObject:
    Type: "AWS::S3::Bucket"
    Properties:
      Bucket: !Ref S3Bucket
      Key: "index.html"
      ContentType: "text/html"
      Body: !Sub |
        { "Fn::ImportValue": "${GitHubExportName}-Content" }

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: !GetAtt S3Bucket.DomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: "index.html"
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: "allow-all"
        Aliases:
          - "example.com"
          - "www.example.com"
