AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fa39983fed2f19c7  # ID образу Amazon Linux 2
      InstanceType: t2.micro  # Тип інстансу EC2, який вибираєте
      UserData:  
        Fn::Base64: !Sub |  
          #!/bin/bash
          yum update -y  # Оновлення системи
          yum install -y docker  # Встановлення Docker
          service docker start  # Запуск сервісу Docker
          docker run -d -p 80:80 nginx  # Запуск контейнера Nginx на порту 80

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance  # Вказуємо, що Elastic IP пов'язаний з інстансом MyEC2Instance

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MySecurityGroup

  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref MyEC2Instance
      NetworkInterfaceId: !Ref MyEC2Instance
      GroupSet:
        - !Ref MySecurityGroup
