Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: landing-service
      Cpu: "256"
      Memory: "512"
      NetworkMode: bridge
      ContainerDefinitions:
        - Name: landing-container
          Image: your-landing-image
          PortMappings:
            - ContainerPort: 80

  ECSLandingService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
