AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a   
      InstanceType: t2.micro
      # Add necessary properties for EC2 Instance 1
      # For example, SecurityGroups, KeyName, UserData, and other configurations

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Add necessary properties for EC2 Instance 2
      # For example, SecurityGroups, KeyName, UserData, and other configurations

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: services.yml
      Parameters:
        # Define parameters as needed for the ECS stack template
        # For example, cluster name, roles, network configurations, etc.
      Tags:
        - Key: key1
          Value: value1
        - Key: key2
          Value: value2
        # Define tags as needed for the ECS stack

  ECSRegisterTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref AWS::ECSStack
      ContainerDefinitions:
        - Name: landing
          Memory: 512
          Essential: true
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          # Add any additional parameters for the landing container
          # For example, Environment, Volumes, Logging, and other configurations

  ECSRegisterEC2Instances:
    Type: AWS::ECS::Service
    Properties:
      Cluster: kurchuster
      TaskDefinition: !Ref ECSRegisterTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
