AWSTemplateFormatVersion: '2010-09-09'

Resources:
  Cluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: kurchuster

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        
IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
    VpcId: your-vpc-id

  EC2Instance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      SecurityGroupIds:
        
!Ref SecurityGroup
    UserData:Fn::Base64: !Sub |#!/bin/bash
        apt-get update
        apt-get install -y software-package# Реєстрація інстансу до кластеру ECS
        echo ECS_CLUSTER=${Cluster} >> /etc/ecs/ecs.config

  EC2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      SecurityGroupIds:
        
!Ref SecurityGroup
    UserData:Fn::Base64: !Sub |#!/bin/bash
        apt-get update
        apt-get install -y software-package# Реєстрація інстансу до кластеру ECS
        echo ECS_CLUSTER=${Cluster} >> /etc/ecs/ecs.config

Outputs:
  EC2Instance1:
    Value: !Ref EC2Instance1
    Export:
      Name: EC2Instance1

  EC2Instance2:
    Value: !Ref EC2Instance2
    Export:
      Name: EC2Instance2
