AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a   
      InstanceType: t2.micro 
      # Додайте необхідні властивості для EC2-інстансу 1 
      # Наприклад, SecurityGroups, KeyName, UserData та інші налаштування

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Додайте необхідні властивості для EC2-інстансу 2
      # Наприклад, SecurityGroups, KeyName, UserData та інші налаштування

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: instances.yml

  ECSRegisterTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref AWS::ECSStack
      ContainerDefinitions:
        - Name: landing
          Memory: 512
          Essential: true
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          # Додайте будь-які додаткові параметри для контейнера лендінгу
          # Наприклад, Environment, Volumes, Logging та інші налаштування

  ECSRegisterEC2Instances:
    Type: AWS::ECS::Service
    Properties:
      Cluster: kurchuster
      TaskDefinition: !Ref ECSRegisterTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
