AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ECSStackParameter1:
    Type: String
    Default: DefaultValue1
    # Додайте додаткові параметри для вкладеного стеку ECS

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a   
      InstanceType: t2.micro
      # Додайте необхідні властивості для EC2-інстансу 1 
      # Наприклад, SecurityGroups, KeyName, UserData та інші налаштування

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Додайте необхідні властивості для EC2-інстансу 2
      # Наприклад, SecurityGroups, KeyName, UserData та інші налаштування

 
   
