Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03aefa83246f44ef2
     
      
     
      Tags:
        - Key: Name
          Value: Instance1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03aefa83246f44ef2
     

      Tags:
        - Key: Name
          Value: Instance2
