AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Add any additional necessary properties for the EC2 instance

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Add any additional necessary properties for the second EC2 instance

  ECSRegisterTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      # Set properties for the Task Definition
      ContainerDefinitions:
        - Name: landing
          # Set properties for the landing container
          Image: nginx:latest
          # Add any necessary parameters for the landing container

  ECSRegisterEC2Instances:
    Type: AWS::ECS::Service
    Properties:
      Cluster: kurchuster
      TaskDefinition: !Ref ECSRegisterTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
