AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Додайте необхідні властивості для EC2-інстансу 

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Додайте необхідні властивості для другого EC2-інстансу

  ECSRegisterTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      # Встановіть властивості для Task Definition
      ContainerDefinitions:
        - Name: landing
          # Встановіть властивості контейнера лендінгу
          Image: nginx:latest
          # Додайте необхідні параметри для контейнера лендінгу

  ECSRegisterEC2Instances:
    Type: AWS::ECS::Service
    Properties:
      Cluster: kurchuster
      TaskDefinition: !Ref ECSRegisterTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
