AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07151644aeb34558a # Замініть на ID AMI, який ви хочете використовувати
      # Додайте необхідні параметри для EC2 інстансу

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07151644aeb34558a # Замініть на ID AMI, який ви хочете використовувати
      # Додайте необхідні параметри для другого EC2 інстансу

  ECSRegisterTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      # Додайте необхідні параметри для Task Definition

  ECSRegisterEC2Instances:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: !Ref ECSRegisterTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-12345678   # Замініть на ID підмережі, до якої бажаєте підключити
          SecurityGroups:
            - sg-12345678      # Замініть на ID групи безпеки, яку бажаєте використовувати
          AssignPublicIp: ENABLED   # Для публічного IP-адреси встановіть значення ENABLED
