AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Add any additional necessary properties for EC2 instance 1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      # Add any additional necessary properties for EC2 instance 2

  ECSRegisterTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: landing
          Memory: 512  # Specify the desired memory for the container
          # Add any other necessary properties for the landing container
          Image: nginx:latest

  ECSRegisterEC2Instances:
    Type: AWS::ECS::Service
    Properties:
      Cluster: kurchuster
      TaskDefinition: !Ref ECSRegisterTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
