AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for creating an EC2 instance with Docker
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-04e601abe3e1a910f
      InstanceType: t2.micro
      KeyName: kurchello 
      Tags:
        - Key: Name
          Value: MyInstance
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          usermod -aG docker $USER
          systemctl start docker

          
           # Запустити контейнер з PhpMyAdmin імеджом
          docker run -d --name phpmyadmin -p 8080:80 -e PMA_ARBITRARY=1 phpmyadmin/phpmyadmin


              # Встановлення Java
          sudo apt-get install -y openjdk-11-jre

          # Встановлення Elasticsearch
          wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
          sudo sh -c 'echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list'
          sudo apt-get update
          sudo apt-get install -y elasticsearch

          # Налаштування Elasticsearch
          sudo systemctl start elasticsearch
          sudo systemctl enable elasticsearch

          # Встановлення Logstash
          sudo sh -c 'echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list'
          sudo apt-get update
          sudo apt-get install -y logstash

          # Налаштування Logstash
          # Ви можете налаштувати конфігураційні файли Logstash відповідно до вашого сценарію використання
           # Завантажити та встановити плагін logstash-input-udp
          sudo /usr/share/logstash/bin/logstash-plugin install logstash-input-udp

          # Створити конфігураційний файл Logstash
          echo 'input {
            udp {
              port => 514
              type => syslog
            }
          }

          filter {
            # Додайте фільтри для обробки логів за потреби
          }

          output {
            elasticsearch {
              hosts => ["localhost:9200"]
              index => "web-app-logs-%{+YYYY.MM.dd}"
            }
          }' | sudo tee /etc/logstash/conf.d/web-app.conf

          # Запустити Logstash
          sudo systemctl start logstash
          sudo systemctl enable logstash

          # Встановлення Kibana
          sudo sh -c 'echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list'
          sudo apt-get update
          sudo apt-get install -y kibana

          # Налаштування Kibana
          sudo systemctl start kibana
          sudo systemctl enable kibana

          # Додайте правила брандмауера, якщо необхідно, щоб дозволити доступ до портів Elasticsearch та Kibana

          # Завантаження та встановлення журналів (за потреби)

          # Рестарт служб для застосування налаштувань
          sudo systemctl restart elasticsearch
          sudo systemctl restart logstash
          sudo systemctl restart kibana
