AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for creating an EC2 instance with Docker
Resources:
  KVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  KSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref KVPC
      CidrBlock: 10.0.0.0/24
  KInternetGateway:
    Type: AWS::EC2::InternetGateway
  KVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref KVPC
      InternetGatewayId: !Ref KInternetGateway
  KRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref KVPC
  KRoute:
    Type: AWS::EC2::Route
    DependsOn: KInternetGateway
    Properties:
      RouteTableId: !Ref KRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref KInternetGateway
  KSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref KSubnet
      RouteTableId: !Ref KRouteTable
  kurchsec:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: kurchsec
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref KVPC
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-04e601abe3e1a910f
      InstanceType: t2.micro
      KeyName: kurchello
      SecurityGroupIds:
        - !Ref kurchsec
      SubnetId: !Ref KSubnet
      Tags:
        - Key: Name
          Value: MyInstance
      UserData:
  Fn::Base64: |
    #!/bin/bash
    # Update the system
    sudo yum update -y

    # Install Java (required for Elasticsearch and Logstash)
    sudo amazon-linux-extras install -y java-openjdk11

    # Import the Elasticsearch GPG key and set up the repository
    sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
    sudo tee /etc/yum.repos.d/elasticsearch.repo <<EOF
    [elasticsearch-7.x]
    name=Elasticsearch repository for 7.x packages
    baseurl=https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck=1
    gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled=1
    autorefresh=1
    type=rpm-md
    EOF

    # Install Elasticsearch, Kibana, and Logstash
    sudo yum install -y elasticsearch kibana logstash

    # Start Elasticsearch, Kibana, and Logstash
    sudo systemctl enable elasticsearch
    sudo systemctl start elasticsearch
    sudo systemctl enable kibana
    sudo systemctl start kibana
    sudo systemctl enable logstash
    sudo systemctl start logstash

    # Install LAMP stack, MariaDB, PHP, and PHPMyAdmin
    sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2 phpmyadmin

    # Configure PHPMyAdmin error handling
    sudo bash -c "echo '\$cfg[\"Error_Handler\"][\"display\"] = false;' >> /etc/phpMyAdmin/config.inc.php"
    sudo bash -c "echo '\$cfg[\"Error_Handler\"][\"parameters\"][\"display\"] = true;' >> /etc/phpMyAdmin/config.inc.php"
    sudo bash -c "echo '\$cfg[\"Error_Handler\"][\"syslog\"] = true;' >> /etc/phpMyAdmin/config.inc.php"

    # Restart Apache web server
    sudo systemctl restart httpd

    # Configure Logstash to parse PHPMyAdmin logs
    sudo tee /etc/logstash/conf.d/phpmyadmin.conf <<EOF
    input {
      file {
        path => "/var/log/phpmyadmin.log"
        start_position => "beginning"
      }
    }
    filter {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
    }
    output {
      elasticsearch {
        hosts => ["localhost:9200"]
        index => "phpmyadmin-%{+YYYY.MM.dd}"
      }
    }
    EOF

    # Restart Logstash
    sudo systemctl restart logstash

    # Create a sample log message for testing
    LOG_FILE=/var/log/phpmyadmin.log
    echo "This is a log message." | sudo tee $LOG_FILE
  KSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH access
      VpcId: !Ref KVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: KSecurityGroup
  KEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance

