AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for creating an EC2 instance with Docker
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-04e601abe3e1a910f
      InstanceType: t2.micro
      KeyName: kurchello 
      Tags:
        - Key: Name
          Value: MyInstance
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          usermod -aG docker $USER
          systemctl start docker

          
           # Запустити контейнер з PhpMyAdmin імеджом
          docker run -d --name phpmyadmin -p 8080:80 -e PMA_ARBITRARY=1 phpmyadmin/phpmyadmin
